### ISSUE TITLE
"Header is invalid"

### ISSUE THREAD

**Issue by userse31** [JakeBlair420/totally-not-spyware#11]
On the iphone 5c, under the captive portal whilst still in OOBE (note to self: don't buy icloud locked stuff off ebay) the error:

"FAIL: header is invalid: 0x4f44213c"

is thrown.

Interestingly, adding "alert(arrayBuf)" right before the check results in what atleast LOOKS "correct" (as in, it looks like the memory safety violation worked).

**Comment by Siguza** [comment]
32-bit is not supported.

**Comment by userse31** [comment]
Is there a variation that is 32 bit?

**Comment by Siguza** [comment]
Not that I know of.
