### ISSUE TITLE
this is pure spam or joke, everytime i execute it IT FAILS TO EVERYTHING

### ISSUE THREAD

**Issue by luixiuno** [JakeBlair420/totally-not-spyware#6]
yall scammers, this is not even a malware or jailbreak

**Comment by PsychoTea** [comment]
comedic excellence

**Comment by Siguza** [comment]
@luixiuno imma go out on a limb here and say you don't know enough to properly set this up.  
But if you're on 10.0-10.3.3, you can go to https://totally-not.spyware.lol and run it from there.
